# Pre-deployment Checklist
name: pre-deployment-checks
version: 1.0.0

# Environment Variables Required
DATABASE_URL=${DATABASE_URL}
DIRECT_URL=${DATABASE_URL}
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
MAILGUN_API_KEY=${MAILGUN_API_KEY}
MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
JWT_SECRET=${JWT_SECRET}
CORS_ORIGIN=${CORS_ORIGIN}
FRONTEND_URL=${FRONTEND_URL}

# Required Services Check
required_services:
  - postgres
  - redis
  - supabase
  - stripe
  - mailgun

# Deployment Configuration
deployment:
  platform: railway
  buildCommand: "npm install && npx prisma generate"
  startCommand: "npm start"
  healthcheck: "/api/health"
  envVarsFile: ".env.railway"
  timeout: 100
